from flask_babel import gettext

nationalities = (
    ('', gettext('Please select your nationality')),
    ('Afghan', gettext('Afghan')),
    ('Albanian', gettext('Albanian')),
    ('Algerian', gettext('Algerian')),
    ('American', gettext('American')),
    ('Andorran', gettext('Andorran')),
    ('Angolan', gettext('Angolan')),
    ('Antiguans', gettext('Antiguans')),
    ('Argentinean', gettext('Argentinean')),
    ('Armenian', gettext('Armenian')),
    ('Australian', gettext('Australian')),
    ('Austrian', gettext('Austrian')),
    ('Azerbaijani', gettext('Azerbaijani')),
    ('Bahamian', gettext('Bahamian')),
    ('Bahraini', gettext('Bahraini')),
    ('Bangladeshi', gettext('Bangladeshi')),
    ('Barbadian', gettext('Barbadian')),
    ('Barbudans', gettext('Barbudans')),
    ('Batswana', gettext('Batswana')),
    ('Belarusian', gettext('Belarusian')),
    ('Belgian', gettext('Belgian')),
    ('Belizean', gettext('Belizean')),
    ('Beninese', gettext('Beninese')),
    ('Bhutanese', gettext('Bhutanese')),
    ('Bolivian', gettext('Bolivian')),
    ('Bosnian', gettext('Bosnian')),
    ('Brazilian', gettext('Brazilian')),
    ('British', gettext('British')),
    ('Bruneian', gettext('Bruneian')),
    ('Bulgarian', gettext('Bulgarian')),
    ('Burkinabe', gettext('Burkinabe')),
    ('Burmese', gettext('Burmese')),
    ('Burundian', gettext('Burundian')),
    ('Cambodian', gettext('Cambodian')),
    ('Cameroonian', gettext('Cameroonian')),
    ('Canadian', gettext('Canadian')),
    ('Cape Verdean', gettext('Cape Verdean')),
    ('Central African', gettext('Central African')),
    ('Chadian', gettext('Chadian')),
    ('Chilean', gettext('Chilean')),
    ('Chinese', gettext('Chinese')),
    ('Colombian', gettext('Colombian')),
    ('Comoran', gettext('Comoran')),
    ('Congolese', gettext('Congolese')),
    ('Costa Rican', gettext('Costa Rican')),
    ('Croatian', gettext('Croatian')),
    ('Cuban', gettext('Cuban')),
    ('Cypriot', gettext('Cypriot')),
    ('Czech', gettext('Czech')),
    ('Danish', gettext('Danish')),
    ('Djibouti', gettext('Djibouti')),
    ('Dominican', gettext('Dominican')),
    ('Dutch', gettext('Dutch')),
    ('Dutchman', gettext('Dutchman')),
    ('Dutchwoman', gettext('Dutchwoman')),
    ('East Timorese', gettext('East Timorese')),
    ('Ecuadorean', gettext('Ecuadorean')),
    ('Egyptian', gettext('Egyptian')),
    ('Emirian', gettext('Emirian')),
    ('Equatorial Guinean', gettext('Equatorial Guinean')),
    ('Eritrean', gettext('Eritrean')),
    ('Estonian', gettext('Estonian')),
    ('Ethiopian', gettext('Ethiopian')),
    ('Fijian', gettext('Fijian')),
    ('Filipino', gettext('Filipino')),
    ('Finnish', gettext('Finnish')),
    ('French', gettext('French')),
    ('Gabonese', gettext('Gabonese')),
    ('Gambian', gettext('Gambian')),
    ('Georgian', gettext('Georgian')),
    ('German', gettext('German')),
    ('Ghanaian', gettext('Ghanaian')),
    ('Greek', gettext('Greek')),
    ('Grenadian', gettext('Grenadian')),
    ('Guatemalan', gettext('Guatemalan')),
    ('Guinea-Bissauan', gettext('Guinea-Bissauan')),
    ('Guinean', gettext('Guinean')),
    ('Guyanese', gettext('Guyanese')),
    ('Haitian', gettext('Haitian')),
    ('Herzegovinian', gettext('Herzegovinian')),
    ('Honduran', gettext('Honduran')),
    ('Hungarian', gettext('Hungarian')),
    ('I-Kiribati', gettext('I-Kiribati')),
    ('Icelander', gettext('Icelander')),
    ('Indian', gettext('Indian')),
    ('Indonesian', gettext('Indonesian')),
    ('Iranian', gettext('Iranian')),
    ('Iraqi', gettext('Iraqi')),
    ('Irish', gettext('Irish')),
    ('Israeli', gettext('Israeli')),
    ('Italian', gettext('Italian')),
    ('Ivorian', gettext('Ivorian')),
    ('Jamaican', gettext('Jamaican')),
    ('Japanese', gettext('Japanese')),
    ('Jordanian', gettext('Jordanian')),
    ('Kazakhstani', gettext('Kazakhstani')),
    ('Kenyan', gettext('Kenyan')),
    ('Kittian and Nevisian', gettext('Kittian and Nevisian')),
    ('Kuwaiti', gettext('Kuwaiti')),
    ('Kyrgyz', gettext('Kyrgyz')),
    ('Laotian', gettext('Laotian')),
    ('Latvian', gettext('Latvian')),
    ('Lebanese', gettext('Lebanese')),
    ('Liberian', gettext('Liberian')),
    ('Libyan', gettext('Libyan')),
    ('Liechtensteiner', gettext('Liechtensteiner')),
    ('Lithuanian', gettext('Lithuanian')),
    ('Luxembourger', gettext('Luxembourger')),
    ('Macedonian', gettext('Macedonian')),
    ('Malagasy', gettext('Malagasy')),
    ('Malawian', gettext('Malawian')),
    ('Malaysian', gettext('Malaysian')),
    ('Maldivan', gettext('Maldivan')),
    ('Malian', gettext('Malian')),
    ('Maltese', gettext('Maltese')),
    ('Marshallese', gettext('Marshallese')),
    ('Mauritanian', gettext('Mauritanian')),
    ('Mauritian', gettext('Mauritian')),
    ('Mexican', gettext('Mexican')),
    ('Micronesian', gettext('Micronesian')),
    ('Moldovan', gettext('Moldovan')),
    ('Monacan', gettext('Monacan')),
    ('Mongolian', gettext('Mongolian')),
    ('Moroccan', gettext('Moroccan')),
    ('Mosotho', gettext('Mosotho')),
    ('Motswana', gettext('Motswana')),
    ('Mozambican', gettext('Mozambican')),
    ('Namibian', gettext('Namibian')),
    ('Nauruan', gettext('Nauruan')),
    ('Nepalese', gettext('Nepalese')),
    ('Netherlander', gettext('Netherlander')),
    ('New Zealander', gettext('New Zealander')),
    ('Ni-Vanuatu', gettext('Ni-Vanuatu')),
    ('Nicaraguan', gettext('Nicaraguan')),
    ('Nigerian', gettext('Nigerian')),
    ('Nigerien', gettext('Nigerien')),
    ('North Korean', gettext('North Korean')),
    ('Northern Irish', gettext('Northern Irish')),
    ('Norwegian', gettext('Norwegian')),
    ('Omani', gettext('Omani')),
    ('Pakistani', gettext('Pakistani')),
    ('Palauan', gettext('Palauan')),
    ('Panamanian', gettext('Panamanian')),
    ('Papua New Guinean', gettext('Papua New Guinean')),
    ('Paraguayan', gettext('Paraguayan')),
    ('Peruvian', gettext('Peruvian')),
    ('Polish', gettext('Polish')),
    ('Portuguese', gettext('Portuguese')),
    ('Qatari', gettext('Qatari')),
    ('Romanian', gettext('Romanian')),
    ('Russian', gettext('Russian')),
    ('Rwandan', gettext('Rwandan')),
    ('Saint Lucian', gettext('Saint Lucian')),
    ('Salvadoran', gettext('Salvadoran')),
    ('Samoan', gettext('Samoan')),
    ('San Marinese', gettext('San Marinese')),
    ('Sao Tomean', gettext('Sao Tomean')),
    ('Saudi', gettext('Saudi')),
    ('Scottish', gettext('Scottish')),
    ('Senegalese', gettext('Senegalese')),
    ('Serbian', gettext('Serbian')),
    ('Seychellois', gettext('Seychellois')),
    ('Sierra Leonean', gettext('Sierra Leonean')),
    ('Singaporean', gettext('Singaporean')),
    ('Slovakian', gettext('Slovakian')),
    ('Slovenian', gettext('Slovenian')),
    ('Solomon Islander', gettext('Solomon Islander')),
    ('Somali', gettext('Somali')),
    ('South African', gettext('South African')),
    ('South Korean', gettext('South Korean')),
    ('Spanish', gettext('Spanish')),
    ('Sri Lankan', gettext('Sri Lankan')),
    ('Sudanese', gettext('Sudanese')),
    ('Surinamer', gettext('Surinamer')),
    ('Swazi', gettext('Swazi')),
    ('Swedish', gettext('Swedish')),
    ('Swiss', gettext('Swiss')),
    ('Syrian', gettext('Syrian')),
    ('Taiwanese', gettext('Taiwanese')),
    ('Tajik', gettext('Tajik')),
    ('Tanzanian', gettext('Tanzanian')),
    ('Thai', gettext('Thai')),
    ('Togolese', gettext('Togolese')),
    ('Tongan', gettext('Tongan')),
    ('Trinidadian or Tobagonian', gettext('Trinidadian or Tobagonian')),
    ('Tunisian', gettext('Tunisian')),
    ('Turkish', gettext('Turkish')),
    ('Tuvaluan', gettext('Tuvaluan')),
    ('Ugandan', gettext('Ugandan')),
    ('Ukrainian', gettext('Ukrainian')),
    ('Uruguayan', gettext('Uruguayan')),
    ('Uzbekistani', gettext('Uzbekistani')),
    ('Venezuelan', gettext('Venezuelan')),
    ('Vietnamese', gettext('Vietnamese')),
    ('Welsh', gettext('Welsh')),
    ('Yemenite', gettext('Yemenite')),
    ('Zambian', gettext('Zambian')),
    ('Zimbabwean', gettext('Zimbabwean'))
)


romantic = (
    ('', gettext('Choisissez vos critères')),
    ('very romantic', gettext('très romantique')),
    ('pretty romantic', gettext('assez romantique')),
    ('not very', gettext('peu romantique')),
    ('not at all', gettext('pas de tout romantique'))
)

marriage = (
    ('', gettext('Choisissez vos critères')),
    ('sacred', gettext('sacré')),
    ('important', gettext('important')),
    ('not necessary', gettext('pas indispensable')),
    ('it\'s not for me', gettext('ce n\'est pas/plus pour moi'))
)

children = (
    ('', gettext('Choisissez vos critères')),
    ('yes', gettext('oui')),
    ('no', gettext('non')),
    ('didn\'t decide yet', gettext('rien n\'est décidé'))
)

body_type = (
    ('', gettext('Choisissez vos critères')),
    ('normal', gettext('normale')),
    ('sportive', gettext('sportive')),
    ('slim', gettext('mince')),
    ('round', gettext('ronde')),
    ('thickset', gettext('trapue'))
)


style = (
    ('', gettext('Choisissez vos critères')),
    ('BCBG', gettext('BCBG')),
    ('trendy', gettext('branché')),
    ('business', gettext('business')),
    ('classic', gettext('classique')),
    ('rock', gettext('rock')),
    ('athletic', gettext('sportif')),
    ('other', gettext('autre'))
)


origin = (
    ('', gettext('Choisissez vos critères')),
    ('european', gettext('européenne')),
    ('african', gettext('africaine')),
    ('arab', gettext('arabe')),
    ('mediterranean', gettext('méditerranéenne')),
    ('métis', gettext('métisse')),
    ('latin', gettext('latine')),
    ('asian', gettext('asiatique')),
    ('indian', gettext('indienne')),
    ('0', gettext('autres'))
)

eyes = (
    ('', gettext('Choisissez vos critères')),
    ('amber', gettext('marron')),
    ('blue', gettext('bleus')),
    ('brown', gettext('noisette')),
    ('gray', gettext('gris')),
    ('green', gettext('verts')),
    ('black', gettext('noirs')),
    ('other', gettext('autres'))
)

hair = (
    ('', gettext('Choisissez vos critères')),
    ('black', gettext('noirs')),
    ('white', gettext('blancs')),
    ('blonde', gettext('blonds')),
    ('red', gettext('roux')),
    ('brown', gettext('bruns')),
    ('other', gettext('autres'))
)

hair_length = (
    ('', gettext('Choisissez vos critères')),
    ('short', gettext('courts')),
    ('long', gettext('longs')),
    ('shoulder length', gettext('mi-longs')),
    ('shaved', gettext('rasés')),
    ('bald', gettext('chauve'))
)

marriage_status = (
    ('', gettext('Choisissez vos critères')),
    ('jamais marié', gettext('jamais marié')),
    ('séparé', gettext('séparé')),
    ('divorcé', gettext('divorcé')),
    ('veuf', gettext('veuf'))
)

smoke = (
    ('', gettext('Choisissez vos critères')),
    ('yes', gettext('oui')),
    ('no', gettext('non')),
    ('occasionally', gettext('oui, occasionnellement')),
    ('trying to stop', gettext('essaye d\'arrêter'))
)

have_children = (
    ('', gettext('Choisissez vos critères')),
    ('no', gettext('non')),
    ('yes', gettext('oui'))
)

live = (
    ('', gettext('Choisissez vos critères')),
    ('alone', gettext('seul')),
    ('colocation', gettext('en colocation')),
    ('with my parents', gettext('avec mes parents'))
)

job = (
    ('', gettext('Choisissez vos critères')),
    ('agriculture', gettext('agriculture')),
    ('architecture', gettext('architecture')),
    ('actor', gettext('acteur')),
    ('administrative sector', gettext('secteur administratif')),
    ('finance sector', gettext('secteur financier')),
    ('government sector', gettext('secteur gouvernemental')),
    ('tourism sector', gettext('secteur du tourisme')),
    ('enginnering sector', gettext("secteur de l'ingénierie")),
    ('marketing sector', gettext('secteur du marketing')),
    ('information technology', gettext('informatique')),
    ('logistics', gettext('logistique')),
    ('doctor', gettext('docteur')),
    ('teacher', gettext('professeur')),
    ('nurse', gettext('infirmière')),
    ('lawyer', gettext('avocat')),
    ('accountant', gettext('comptable')),
    ('social assistance', gettext('Assistance sociale')),
    ('business', gettext('entrepreneur')),
    ('other', gettext('other')),
)

religion = (
    ('', gettext('Choisissez vos critères')),
    ('agnostique', gettext('agnostique')),
    ('athée', gettext('athée')),
    ('bouddhiste', gettext('bouddhiste')),
    ('catholique', gettext('catholique')),
    ('chrétien', gettext('chrétien')),
    ('hindouiste', gettext('hindouiste')),
    ('israélite', gettext('israélite')),
    ('musulman', gettext('musulman')),
    ('orthodoxe', gettext('orthodoxe')),
    ('protestant', gettext('protestant')),
    ('spirituel', gettext('spirituel')),
    ('autre', gettext('autre')),
    ('0', gettext('je le garde pour moi'))
)

eat = (
    ('', gettext('Choisissez vos critères')),
    ('everything', gettext('mange de tout')),
    ('healthy food', gettext('nourriture saine')),
    ('diet', gettext('diet')),
    ('vegetarian', gettext('végétarien')),
    ('kosher', gettext('casher')),
    ('hallal', gettext('hallal')),
    ('other', gettext('autres'))
)

pet = (
    ('', gettext('Choisissez vos critères')),
    ('cat', gettext('chats')),
    ('dog', gettext('chiens')),
    ('bird', gettext('oiseaux')),
    ('exotic animals', gettext('animaux exotiques')),
    ('pisces', gettext('poissons')),
    ('rodents', gettext('rongeurs')),
    ('rabbit', gettext('lapins')),
    ('I do not have any animal', gettext('je ne possède pas d\'animal')),
    ('other', gettext('autres animaux'))
)

speak = (
    ('', gettext('Vous parlez')),
    ('French', gettext('French')),
    ('Dutch', gettext('Dutch')),
    ('German', gettext('German')),
    ('Spanish', gettext('Spanish')),
    ('English', gettext('English')),
    ('Arabic', gettext('Arabic')),
    ('Portuguese', gettext('Portuguese')),
    ('Mandarin', gettext('Mandarin')),
    ('Hindi', gettext('Hindi')),
    ('Bengali', gettext('Bengali')),
    ('Russian', gettext('Russian')),
    ('Japanese', gettext('Japanese')),
    ('Punjabi', gettext('Punjabi')),
    ('Javanese', gettext('Javanese')),
    ('Wu', gettext('Wu')),
    ('Malay', gettext('Malay')),
    ('Telugu', gettext('Telugu')),
    ('Vietnamese', gettext('Vietnamese')),
    ('Korean', gettext('Korean')),
    ('Marathi', gettext('Marathi')),
    ('Tamil', gettext('Tamil')),
    ('Urdu', gettext('Urdu')),
    ('Turkish', gettext('Turkish')),
    ('Italian', gettext('Italian')),
    ('Yue', gettext('Yue')),
    ('Thai', gettext('Thai')),
    ('Gujarati', gettext('Gujarati')),
    ('Jin', gettext('Jin')),
    ('Southern Min', gettext('Southern Min')),
    ('Persian', gettext('Persian')),
    ('Polish', gettext('Polish')),
    ('Pashto', gettext('Pashto')),
    ('Kannada', gettext('Kannada')),
    ('Xiang', gettext('Xiang')),
    ('Malayalam', gettext('Malayalam')),
    ('Sundanese', gettext('Sundanese')),
    ('Hausa', gettext('Hausa')),
    ('Odia', gettext('Odia')),
    ('Burmese', gettext('Burmese')),
    ('Hakka', gettext('Hakka')),
    ('Ukrainian', gettext('Ukrainian')),
    ('Bhojpuri', gettext('Bhojpuri')),
    ('Tagalog', gettext('Tagalog')),
    ('Yoruba', gettext('Yoruba')),
    ('Maithili', gettext('Maithili')),
    ('Uzbek', gettext('Uzbek')),
    ('Sindhi', gettext('Sindhi')),
    ('Amharic', gettext('Amharic')),
    ('Fula', gettext('Fula')),
    ('Romanian', gettext('Romanian')),
    ('Oromo', gettext('Oromo')),
    ('Igbo', gettext('Igbo')),
    ('Azerbaijani', gettext('Azerbaijani')),
    ('Awadhi', gettext('Awadhi')),
    ('Gan Chinese', gettext('Gan Chinese')),
    ('Cebuano', gettext('Cebuano')),
    ('Kurdish', gettext('Kurdish')),
    ('Serbo-Croatian', gettext('Serbo-Croatian')),
    ('Malagasy', gettext('Malagasy')),
    ('Saraiki', gettext('Saraiki')),
    ('Nepali', gettext('Nepali')),
    ('Sinhalese', gettext('Sinhalese')),
    ('Chittagonian', gettext('Chittagonian')),
    ('Zhuang', gettext('Zhuang')),
    ('Khmer', gettext('Khmer')),
    ('Turkmen', gettext('Turkmen')),
    ('Assamese', gettext('Assamese')),
    ('Madurese', gettext('Madurese')),
    ('Somali', gettext('Somali')),
    ('Marwari', gettext('Marwari')),
    ('Magahi', gettext('Magahi')),
    ('Haryanvi', gettext('Haryanvi')),
    ('Hungarian', gettext('Hungarian')),
    ('Chhattisgarhi', gettext('Chhattisgarhi')),
    ('Greek', gettext('Greek')),
    ('Chewa', gettext('Chewa')),
    ('Deccan', gettext('Deccan')),
    ('Akan', gettext('Akan')),
    ('Kazakh', gettext('Kazakh')),
    ('Northern Min', gettext('Northern Min')),
    ('Sylheti', gettext('Sylheti')),
    ('Zulu', gettext('Zulu')),
    ('Czech', gettext('Czech')),
    ('Kinyarwanda', gettext('Kinyarwanda')),
    ('Dhundhari', gettext('Dhundhari')),
    ('Haitian Creole', gettext('Haitian Creole')),
    ('Eastern Min', gettext('Eastern Min')),
    ('Ilocano', gettext('Ilocano')),
    ('Quechua', gettext('Quechua')),
    ('Kirundi', gettext('Kirundi')),
    ('Swedish', gettext('Swedish')),
    ('Hmong', gettext('Hmong')),
    ('Shona', gettext('Shona')),
    ('Uyghur', gettext('Uyghur')),
    ('Hiligaynon/Ilonggo', gettext('Hiligaynon/Ilonggo')),
    ('Mossi', gettext('Mossi')),
    ('Xhosa', gettext('Xhosa')),
    ('Belarusian', gettext('Belarusian')),
    ('Balochi', gettext('Balochi')),
    ('Konkani', gettext('Konkani'))
)

education = (
    ('', gettext('Choisissez vos critères')),
    ('high school', gettext('études secondaires')),
    ('bachelor', gettext('bachelier')),
    ('master\'s', gettext('master (Licence)')),
    ('doctorate', gettext('doctorat')),
    ('0', gettext('je le garde pour moi'))
)

income = (
    ('', gettext('Choisissez vos critères')),
    ('-10,000 euros/year', gettext('- de 10.000 euros/an')),
    ('from 10 to 20,000 euros/year', gettext('de 10 à 20.000 euros/an')),
    ('from 20 to 30,000 euros/year', gettext('de 20 à 30.000 euros/an')),
    ('from 30 to 50,000 euros/year', gettext('de 30 à 50.000 euros/an')),
    ('from 50 to 75,000 euros/year', gettext('de 50 à 75.000 euros/an')),
    ('from 75 to 100,000 euros/year', gettext('de 75 à 100.000 euros/an')),
    ('more than 100,000 euros/year', gettext('plus de 100.000 euros/an')),
    ('0', gettext('je le garde pour moi'))
)
